messaging/config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :sms_messages, only: [:index]

end

messaging/app/models/account.rb
class Account < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :users
  has_many :sms_messages
end

messaging/app/models/sms_message.rb
class SmsMessage < ActiveRecord::Base
  belongs_to :account
  validates :account, presence: true

  belongs_to :user

  scope :unread, -> { where(unread: true) }
  scope :outbound, -> { where(outbound: true) }
  scope :sorted, -> { order(created_at: :desc) }
end

messaging/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :account
  validates  :account, presence: true

  has_many :sms_messages

  # Skip all the Devise stuff for now

  validates :name, presence: true

  validates :email, presence: true, uniqueness: true
end

messaging/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :stub_user!

  protected

  def stub_user!
    @account = Account.first
    @user    = @account.users.first
  end
end

messaging/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

messaging/app/controllers/sms_messages_controller.rb
class SmsMessagesController < ApplicationController
  def index
    @sms_messages = @account.sms_messages.sorted.includes([:user, :account]).all
  end
end

messaging/app/helpers/dashboard_helper.rb
module DashboardHelper
end

messaging/app/views/dashboard/index.html.erb
<%= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true).
render(File.read(Rails.root.join("README.md"))).html_safe %>

messaging/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OnboardIQ Test: Messages" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>>OnboardIQ Test: Messages</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Messages", sms_messages_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Signed In as</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Account: <%= @account.name %></li>
              <li><%= @user.name %> (<%= @user.email %>)</li>
              <li>Unread messages: <%= @account.sms_messages.unread.size %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy;</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

messaging/app/views/sms_messages/index.html.erb
<%- model_class = SmsMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:message_sid) %></th>
      <th><%= model_class.human_attribute_name(:from_number) %></th>
      <th><%= model_class.human_attribute_name(:to_number) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:outbound) %></th>
      <th><%= model_class.human_attribute_name(:unread) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @sms_messages.each do |sms_message| %>
      <tr>
        <td><%= sms_message.user.name %></td>
        <td><%= sms_message.message_sid %></td>
        <td><%= sms_message.from_number %></td>
        <td><%= sms_message.to_number %></td>
        <td><%= sms_message.body %></td>
        <td><%= sms_message.outbound %></td>
        <td><%= sms_message.unread %></td>
        <td><%=l sms_message.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>